feat: add constant propagation for different unary and binary ops.
Xilinx/onnx-mlir pull request #121
Opened 2024-07-02 09:39 UTC by ttjost

We now support: `bitwise_(not/and/or), logical_(not,and,or,xor), clip, ceil, floor, sin, cos, log, erf, exp, not`.

I will open a PR upstream in the coming weeks.

2024-07-02 11:58 UTC, mgehre-amd commented
> We now support: `bitwise_(not/and/or), logical_(not,and,or,xor), clip, ceil, floor, sin, cos, log, erf, exp, not`.
> 
> I will open a PR upstream in the coming weeks.

Can you please open the upstream PR right away after this one merged?

2024-07-02 11:59 UTC, mgehre-amd commented on src/Dialect/ONNX/Transforms/ConstProp.cpp
> +  // Return 'value' if exists, as there is no need to clip to lowest or largest.
I don't understand this case, could you please explain on which IR this happens?

2024-07-02 12:02 UTC, mgehre-amd commented on src/Dialect/ONNX/Transforms/ConstProp.cpp
> +  static T eval(T val) { return 1 / val; }
Can `T` be integer here?  Would that crash when `val` is zero?

2024-07-02 12:04 UTC, mgehre-amd commented on src/Dialect/ONNX/Transforms/ConstProp.td
> +    // To min(max(c0, c1), c2).
I'm not sure if this behavior is the correct one when `min` > `max` (see https://github.com/onnx/onnx/issues/6165)
To be safe, could you not constant fold in that case?

2024-07-02 12:05 UTC, mgehre-amd commented on src/Dialect/ONNX/Transforms/ConstProp.cpp
> +  return CreateMaxOrMinForClip(rewriter, type, value, llvm::APFloat::getLargest,
Why is `llvm::APFloat::getLargest` correct here?

2024-07-02 12:08 UTC, mgehre-amd commented on src/Dialect/ONNX/Transforms/ConstProp.cpp
> +Value CreateMaxOrMinForClip(PatternRewriter &rewriter, ShapedType type,
I find the `MaxOrMin` names in this function more confusion than helpful. Maybe it would be clearer if you move the 
```
 if (!isNoneValue(value))
    return value;
```
to the caller and rename this function to `getConstantOfType(rewriter, type, getFpValue, getIntValue)`

2024-07-02 12:10 UTC, mgehre-amd requested changes
Looks like a lot of work, thanks! Just a few comments

2024-07-02 12:36 UTC, ttjost commented on src/Dialect/ONNX/Transforms/ConstProp.cpp
> +  return CreateMaxOrMinForClip(rewriter, type, value, llvm::APFloat::getLargest,
Because we also pass `isNegative` which gives us the lowest value. `getLowest` seems to be done with `getLargest` plus `isNegative`.

2024-07-02 12:45 UTC, ttjost commented on src/Dialect/ONNX/Transforms/ConstProp.td
> +    // To min(max(c0, c1), c2).
Yep, I know. In one of the LIT tests, I also added the issue you reported in a comment. But I can certainly make sure we don't fold in that case.

2024-07-02 16:30 UTC, ttjost commented on src/Dialect/ONNX/Transforms/ConstProp.td
> +    // To min(max(c0, c1), c2).
I added a new constraint to check for Min < Max (`satisfiesMinLessThanMaxRequirement`). This constraint will make use of the infra to check for cases where we need to expand values, say, when we have `min = [2.0]` being compared with `max=[3.0, 3.0, 0.0]`.

2024-07-03 06:22 UTC, mgehre-amd approved these changes

2024-07-03 06:22 UTC, merged