Update LLVM/MHLO to week of 2022/11/14
Xilinx/onnx-mlir pull request #2
Opened 2022-12-06 16:03 UTC by gargaroff

Green LLVM commit: e864ac694540342d5e59f59c525c5082f2594fb8
Green MHLO commit: eab364ba2a66bd0613efb94f8a738c1c97aaee92

The commits listed above are the green commits from Nov. 14.

Changelog:

mlir-hlo changed their directory structure, requiring two `include_directories` directives to make it buildable.
Generation of `#map` has changed, requiring large NFC changes to test references.

2022-12-07 11:29 UTC, ljfitz requested changes
There are many ref changes that seem unnecessary, making it very difficult to see what has actually changed.

2022-12-07 11:29 UTC, ljfitz commented on test/mlir/conversion/krnl_to_affine/buffer_copy.mlir
> +// CHECK-DAG: #map = affine_map<(d0, d1) -> (d0, d1)>
Is this map used in any other lines being checked? If not, why are we checking it?

2022-12-07 11:29 UTC, ljfitz commented on test/mlir/conversion/krnl_to_affine/buffer_copy.mlir
> +// CHECK-DAG: #map2 = affine_map<()[s0] -> (-s0 + 56, 6)>
Would it be sensible to use symbolic match names here?

2022-12-07 11:29 UTC, ljfitz commented on test/mlir/onnx/onnx_lowering_with_canonicalize.mlir
> +// CHECK:           krnl.iterate([[LOOP_0_]]#0, [[LOOP_0_]]#1) with ([[LOOP_0_]]#0 -> [[I_0_:%.+]] = 0 to 2, [[LOOP_0_]]#1 -> [[I_1_:%.+]] = 0 to 3){
Why the change of variable names? It seems to unnecessarily complicate the review.

2022-12-07 15:25 UTC, gargaroff commented on test/mlir/conversion/krnl_to_affine/buffer_copy.mlir
> +// CHECK-DAG:   [[MAP_0_:#.+]] = affine_map<(d0, d1) -> (d0, d1)>
missed this

2022-12-07 15:26 UTC, gargaroff commented on test/mlir/conversion/krnl_to_affine/buffer_copy.mlir
> +// CHECK-DAG:   [[MAP_3_:#.+]] = affine_map<()[s0] -> (-s0 + 56, 6)>
rename this to match old name

2022-12-07 15:26 UTC, gargaroff commented on test/mlir/conversion/krnl_to_affine/buffer_copy.mlir
> +// CHECK-DAG:   [[MAP_1_:#.+]] = affine_map<(d0) -> (-d0 + 45, 10)>
rename

2022-12-07 15:26 UTC, gargaroff commented on test/mlir/conversion/krnl_to_affine/buffer_copy.mlir
> +// CHECK-DAG:   [[MAP_2_:#.+]] = affine_map<()[s0] -> (-s0 + 56, 6)>
rename

2022-12-07 15:26 UTC, gargaroff commented on test/mlir/krnl/krnl_memset.mlir
> +// CHECK-DAG: [[MAP_2_:#.+]] = affine_map<()[s0] -> (s0 ceildiv 64)>
rename

2022-12-07 15:34 UTC, gargaroff commented
Glad you made me do this @ljfitz. It was huge pain in the butt and my fingers hurt from copy-search-select-pasting so much, but it was definitely worth it, looking at the diff now 😄

2022-12-07 15:36 UTC, ljfitz commented on test/mlir/krnl/krnl_enable_memory_pool.mlir
> +// CHECK: [[MAP:#.+]] = affine_map<(d0, d1) -> (0, d1 floordiv 64, 0, d0 floordiv 32, d0 mod 32, d1 mod 64)
Do you know where this change came from?

2022-12-07 15:38 UTC, ljfitz commented on test/mlir/onnx/onnx_lowering.mlir
> +  // CHECK: krnl.iterate([[DEF_LOOPS]]#0, [[DEF_LOOPS]]#1) with ([[DEF_LOOPS]]#0 -> %arg1 = 0 to #map1([[DIM_2]]), [[DEF_LOOPS]]#1 -> %arg2 = 0 to 10){
Was it not sensible to address this file with the `[[MAP:#.+]] =` approach?

2022-12-07 15:41 UTC, gargaroff commented on test/mlir/onnx/onnx_lowering.mlir
> +  // CHECK: krnl.iterate([[DEF_LOOPS]]#0, [[DEF_LOOPS]]#1) with ([[DEF_LOOPS]]#0 -> %arg1 = 0 to #map1([[DIM_2]]), [[DEF_LOOPS]]#1 -> %arg2 = 0 to 10){
nope, simply missed this file

2022-12-07 15:43 UTC, ljfitz approved these changes
This looks good for upstreaming, I'd expect a question about the `affine_map<(d0, d1) -> (0, d1 floordiv 64, 0, d0 floordiv 32, d0 mod 32, d1 mod 64)` change, so if you already know where it came from you should add a review comment to explain,

2022-12-08 13:32 UTC, ljfitz commented
Closed in favor of https://github.com/onnx/onnx-mlir/pull/ 1905

2022-12-08 13:32 UTC, closed without merging