Add folder to ONNXReduceMean operation
Xilinx/onnx-mlir pull request #224
Opened 2024-12-02 14:50 UTC by mathmer-amd

2024-12-03 17:43 UTC, ttjost commented on src/Dialect/ONNX/ONNXOps/Math/Reduction.cpp
> +  for (bool red : shapeHelper.isReductionAxis) {
I wonder if you could use `llvm::count_if`:
```suggestion
  nbAxesToReduce = llvm::count_if(shapeHelper.isReductionAxis, [&](auto reductionAxis)) {
  return reductionAxis;
  });
```

2024-12-03 17:43 UTC, ttjost approved these changes
tiny little comment. Thanks!

2024-12-04 08:17 UTC, ehsan-toosi approved these changes

2024-12-04 08:17 UTC, ehsan-toosi commented on src/Dialect/ONNX/ONNXOps/Math/Reduction.cpp
> +  for (bool red : shapeHelper.isReductionAxis) {
Continuing on what Tiago suggested, I'd say use a bool (like hasReduction) instead of int and use llvm::any_of instead of llvm::count_if

2024-12-04 08:18 UTC, ehsan-toosi requested changes
ONNXOps.td.inc is auto generated. You have to modify the generator of it.

2024-12-04 08:22 UTC, ehsan-toosi commented
This is the file that you have to modify:
[utils/gen_onnx_mlir.py](https://github.com/Xilinx/onnx-mlir/blob/feature/onnx-to-tosa/utils/gen_onnx_mlir.py)

2024-12-05 13:50 UTC, mathmer-amd commented on utils/gen_onnx_mlir.py
> +    "GridSample",
For reviewers, this is an oversight from an older PR.

2024-12-05 13:51 UTC, mathmer-amd commented on src/Dialect/ONNX/ONNXOps/Math/Reduction.cpp
> +  for (bool red : shapeHelper.isReductionAxis) {
that's a good idea! thanks!

2024-12-06 07:38 UTC, jorickert approved these changes

2024-12-06 07:38 UTC, jorickert commented on src/Dialect/ONNX/ONNXOps.td.inc
> +  [Pure, OpVersionTrait<20>, DeclareOpInterfaceMethods<ShapeInferenceOpInterface>, DeclareOpInterfaceMethods<ShapeHelperOpInterface>]> {
This seems to have been wrong before, now the OpVersion fits the op 👍

2024-12-06 07:38 UTC, jorickert commented on src/Dialect/ONNX/ONNXOps.td.inc
> -  let results = (outs AnyTypeOf<[TensorOf<[F16]>, TensorOf<[F32]>, TensorOf<[F64]>, TensorOf<[BF16]>]>:$Y);
Please revert this change, according to the comment above, bf16 support was added on purpose

2024-12-06 07:38 UTC, jorickert commented on src/Dialect/ONNX/ONNXOps.td.inc
A bit surprised about all the whitespace changes, but looks correct and inline with upstream

2024-12-06 07:38 UTC, jorickert commented on test/mlir/onnx/onnx_recompose.mlir
> -  %mean = "onnx.ReduceMean"(%x, %none) {keepdims = 1 : si64, noop_with_empty_axes = 1: si64} : (tensor<1x384x768xf32>, none) -> tensor<1x384x1xf32>
Nice catch 👍

2024-12-06 08:41 UTC, mathmer-amd commented on src/Dialect/ONNX/ONNXOps.td.inc
> -  let results = (outs AnyTypeOf<[TensorOf<[F16]>, TensorOf<[F32]>, TensorOf<[F64]>, TensorOf<[BF16]>]>:$Y);
it's my bad, I forgot this one, I will add it back. Thank for catching it!

2024-12-06 10:03 UTC, ehsan-toosi approved these changes

2024-12-10 13:05 UTC, jorickert commented on third_party/stablehlo
please do not bump this

2024-12-10 13:27 UTC, mathmer-amd commented on third_party/stablehlo
okayy, I change this

2024-12-10 13:49 UTC, merged