ONNXToTOSA: Batchnormalization
Xilinx/onnx-mlir pull request #64
Opened 2024-03-22 09:24 UTC by ge28boj

2024-03-22 09:59 UTC, mgehre-amd requested changes
Generally looks good.
Would be great if we could extend the testing to cover the whole op specification.

2024-03-22 09:59 UTC, mgehre-amd commented on test/mlir/conversion/onnx_to_tosa/NN/BatchNorm.mlir
> +
Could you please add one test case for bf16, f16 & f64? Those are all legal types for BatchNorm.

The .td file shows that BatchNormalizationInferenceMode also accepts a momentum attribute. Can you please add a test case with that?

2024-03-22 09:59 UTC, mgehre-amd commented on src/Conversion/ONNXToTOSA/NN/BatchNorm.cpp
> +      // input/output tensor is 4
```suggestion
      // The layout of the output is N x C x D1 x D2 … Dn. For batch normalization, the C
      // dimension is kept. The new shape should be {1, C, 1, 1, ...}.
```

2024-03-22 09:59 UTC, mgehre-amd commented on src/Conversion/ONNXToTOSA/NN/BatchNorm.cpp
> +      for (auto i = 2; i < outTensorType.getRank(); i++) {
nit: LLVM style is to elide braces when the body is a single line

2024-03-22 09:59 UTC, mgehre-amd commented on src/Conversion/ONNXToTOSA/NN/BatchNorm.cpp
> +      auto newType =
Is this the same as outType?

2024-03-22 10:38 UTC, ttjost commented on src/Conversion/ONNXToTOSA/NN/BatchNorm.cpp
> +  auto op1SubInputMean =
Could you also make use of `tosabuilder` here?

2024-03-22 10:39 UTC, ttjost commented on src/Conversion/ONNXToTOSA/NN/BatchNorm.cpp
> +    auto reshapeToInputDim = [&](Operation *op,
If you use tosabuilder, I think this function is not necessary. Everything is handled for free. Let me know if you need to discuss about it.

2024-03-22 10:40 UTC, ttjost requested changes
Could you please use `tosabuilder`? That will make things easier.

2024-03-25 14:19 UTC, mgehre-amd approved these changes

2024-03-26 08:24 UTC, roberteg16 approved these changes
LGTM

2024-03-26 08:24 UTC, roberteg16 commented on test/mlir/conversion/onnx_to_tosa/NN/BatchNorm.mlir
> +// CHECK:           return [[VAR_4_]] : tensor<100x3x10x10xf64>
Normally when we want to check that a legalization did not happen it is enough if you check that the op is still there:

```suggestion
//     CHECK: onnx.BatchNormalizationInferenceMode
// CHECK-NOT: tosa
```

2024-03-26 08:24 UTC, roberteg16 commented on test/mlir/conversion/onnx_to_tosa/NN/BatchNorm.mlir
> +// CHECK-DAG:       [[VAR_6_:%.+]] = tosa.reshape [[VAR_1_]] {new_shape = array<i64: 1, 3, 1, 1>} : (tensor<3xbf16>) -> tensor<1x3x1x1xbf16>
NIT: Usually we take into consideration the semantics of the op when we write the test. Reshapes can be simplified to:

``` suggestion
// CHECK-DAG:       [[VAR_4_:%.+]] = tosa.reshape [[VAR_2_]] {new_shape = array<i64: 1, 3, 1, 1>} : (tensor<3xbf16>)
// CHECK-DAG:       [[VAR_5_:%.+]] = tosa.reshape [[VAR_0_]] {new_shape = array<i64: 1, 3, 1, 1>} : (tensor<3xbf16>)
// CHECK-DAG:       [[VAR_6_:%.+]] = tosa.reshape [[VAR_1_]] {new_shape = array<i64: 1, 3, 1, 1>} : (tensor<3xbf16>)
```

2024-03-26 08:24 UTC, roberteg16 commented on src/Conversion/ONNXToTOSA/NN/BatchNorm.cpp
> +    reshapedVar = tosaBuilder.reshape(var, llvm::ArrayRef<int64_t>(newShape));
NIT: I believe you can remove `llvm::`

2024-03-26 16:48 UTC, ttjost approved these changes

2024-03-26 19:13 UTC, merged