feat(ONNXToTosa): support onnx.Expand through tosa.tile.
Xilinx/onnx-mlir pull request #79
Opened 2024-04-16 15:49 UTC by ttjost

Spec for onnx.Expand: https://onnx.ai/onnx/operators/onnx__Expand.html

2024-04-16 16:04 UTC, mgehre-amd commented on test/mlir/conversion/onnx_to_tosa/Math/Elementwise.mlir
> +  %0 = "onnx.Expand"(%arg0, %arg1) {onnx_node_name = "Expand_335"} : (tensor<1x64x1x1xf32>, tensor<4xi64>) -> tensor<1x64x64x64xf32>
Isn't the result type illegal, i.e. the ONNX op is illegal in itself? I think we should only have legal IR as input in tests.

2024-04-16 16:04 UTC, mgehre-amd commented on test/mlir/conversion/onnx_to_tosa/Math/Elementwise.mlir
> +  %1 = "onnx.Expand"(%arg0, %0) {onnx_node_name = "Expand_335"} : (tensor<1x64x1x1xf32>, tensor<4xi64>) -> tensor<1x64x64x64xf32>
Can you please remove the `{onnx_node_name = "Expand_335"}` here and below?

2024-04-16 16:05 UTC, mgehre-amd approved these changes

2024-04-17 13:05 UTC, cmcgirr-amd commented on src/Conversion/ONNXToTOSA/Math/Elementwise.cpp
> +    rewriter.replaceOpWithNewOp<mlir::tosa::TileOp>(
I don't think we can implement `onnx.Expand` generically with just the `tosa.TileOp`. AFAICS the tile op replicates the content of each dimension y amount of times. And onnx.Expand broadcast to that given shape. 

So the rank of `tosa.Tile` is the same for Input and Output, but onnx.Expand can have different rank at the output. And the shape array of onnx.Expand does not equal the `multiples` argument of the tileop. 

I think for unequal rank cases we need a reshape. So for:
```
Onnx.Expand(tensor<3x1>, [15, 3, 5]) -> tensor<15x3x5>
```
We would want:
```
x = tosa.reshape(tensor<3x1>, [1x3x1]) -> tensor<1x3x1>
tosa.reshape(y, [15, 1, 5]) -> tensor<15x3x5>
```

2024-04-17 13:10 UTC, cmcgirr-amd requested changes
I think we need to either restrict the conversion to the versions of expand that Tile can support directly or try to make it work for all scenarios.

2024-05-14 10:22 UTC, mgehre-amd commented
@ttjost, is it likely that you will work on this PR soon?

2024-08-08 13:50 UTC, flemairen6 commented
Opened https://github.com/Xilinx/onnx-mlir/pull/150 to lower Expand using a different decomposition. I didn't reuse this PR because I basically restarted from zero.

2024-08-12 06:59 UTC, closed without merging